### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by occoder** [LaboratoireMecaniqueLille/crappy#128]
Hi
Considering the Crappy package heavily relies on multi-process and pipe as the IPC method, is possible to deploy a Crappy based application within a Docker container?

**Comment by WeisLeDocto** [comment]
Hi !
I'm not familiar with Docker, but AFAIU it should normally be possible to use Crappy inside a container. The number of CPU cores the container is allowed to access will be critical for parallelism, but that's apparently something that can be configured easily.
Because Docker runs in a VM on Windows and macOS, I would expect lower performance in this case. Access to USB and other ports might also need to be configured.
See these SO question: 
https://stackoverflow.com/questions/47989418/multiprocessing-python-program-inside-docker
https://stackoverflow.com/questions/24225647/docker-a-way-to-give-access-to-a-host-usb-or-serial-device

Note: for this type of question, which is not properly speaking an issue or a feature request, you should consider using the [Discussions](https://github.com/LaboratoireMecaniqueLille/crappy/discussions) section. It is designed for discussion threads, with an interface similar to SO.
