### ISSUE TITLE
Interacting with plot window changes plot (Grapher)

### ISSUE THREAD

**Issue by ForestRupicolous** [LaboratoireMecaniqueLille/crappy#43]
Hi,

Im on a Laptop (i5-1145G7) under Windows. When I use a basic example and plot some data with the Grapher block the output is influenced when I interact with the plot. When moving the window or try to save the plot, the plot is paused and the data is only partially logged. After the interaction is over the plot continues but some data is missing. I tried to show this in the pictures below.

With version 1.5.10 I get multiple `WARNING : Timeout error in pipe send! ` messages but these are not visible in 2.0.0dev2.

Maybe it is about my CPU or there are some settings I have to use to avoid this? Maybe this is also a matplotlib issue as I'm not aware of many live-plot examples. The one I found is not parallel, therefore there is no difference in the plot as the whole thing just stops.

What I would expect is that even when the stream stops (e.g. saving a figure) afterwards the missing data is enterd (e.g. from a buffer).
 
This is the normal output:
![Figure_1](https://github.com/LaboratoireMecaniqueLille/crappy/assets/45405985/5d4e37b8-4055-4e4c-91d4-9ad71a8e23e1)

This is the same plot later. The visible error occured while I deliberatly took some time saveing the first picture.
![Figure_2](https://github.com/LaboratoireMecaniqueLille/crappy/assets/45405985/85059319-f7a8-4e8a-aff0-cdffe8d19a76)

Additionally it looks like the frequency of the complete system drops:
```
2023-08-30 16:56:06,460 crappy.Generator-1 INFO     loops/s: 95.90516503525168
2023-08-30 16:56:08,411 crappy.Generator-2 INFO     loops/s: 185.6397901934411
2023-08-30 16:56:08,465 crappy.Generator-1 INFO     loops/s: 95.76832549223734
----- me holding the gui window ----
2023-08-30 16:56:33,055 crappy.Grapher-1 INFO     loops/s: 0.07501388747301645
2023-08-30 16:56:33,056 crappy.Generator-1 INFO     loops/s: 5.1238129068350355 
2023-08-30 16:56:33,057 crappy.Generator-2 INFO     loops/s: 8.358162379193692
----- end of interaction -----
2023-08-30 16:56:35,056 crappy.Grapher-1 INFO     loops/s: 1.999565219049508
2023-08-30 16:56:35,062 crappy.Generator-2 INFO     loops/s: 185.5695355424737
2023-08-30 16:56:35,062 crappy.Generator-1 INFO     loops/s: 95.73176961980535
```

Thank you!

Martin

**Comment by WeisLeDocto** [comment]
Hi Martin !

`matplotlib` giving a hard time to the CPU is definitely something we've been struggling with for a while. However, most alternatives like `PyQtGraph` rely on event loops that do not blend well with the multiprocessing architecture of Crappy. [Bokeh](https://github.com/bokeh/bokeh) seems to be the most promising replacement library, but integrating it in Crappy hasn't been a top priority so far.

Regarding your specific problem, it has several causes. 

- First, each time the `loop()` method of the Grapher Block is called, it receives the incoming data and updates the graph. 
- Second, dragging the Grapher window or using its embedded options results in a blockage somewhere in the `loop()` method. It means the data stops being received. 
- And third, the [Pipe](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe) that carries the data from the Generator to the Grapher has a limited bandwidth and can overflow. 

In your case, the data sent while you're moving the window around is basically lost because it doesn't fit in the `Pipe` (Link) that is already overflowing. This is the meaning of the `WARNING` you get.

So, how can you limit the interference ? 

- First, avoid playing too much with the Grapher windows. The `window_size` and `window_pos` arguments should allow you to arrange a nice window layout from the start. 
- Also, if you want to save beautiful curves, it is probably better to first save your data with a Recorder Block and then plot it once your tests are over.
- And finally, you can try to decrease the amount of data sent to the Grapher Block. In most cases there's no need to plot more than a few points / second, here your Generators send 95 and 185 pts/s respectively ! If possible, you can decrease the looping frequency of the Generator (`freq` argument). If for some reason you need a high looping frequency, the Mean or Median Modifiers can be an option for reducing the data rate on a given Link.

Hope this helps !
Weis

**Comment by ForestRupicolous** [comment]
Hi Weis,
thank you for the detailed response. I will try the tipps you gave. I think recording first will work best in my case. Its good to see that there are already multiple possible solutions in place.
I understand that it isn't your priority so just out of interest: Have you seen the matplotlib animation example [Oscilloscope](https://matplotlib.org/stable/gallery/animation/strip_chart.html)
When I change the update function like this:
 ```
def update(self, y):
        lastt = self.tdata[-1]
        self.ax.set_xlim(self.tdata[0], lastt)
        self.ax.figure.canvas.draw()

        # This slightly more complex calculation avoids floating-point issues
        # from just repeatedly adding `self.dt` to the previous value.
        t = self.tdata[0] + len(self.tdata) * self.dt

        self.tdata.append(t)
        self.ydata.append(y)
        self.line.set_data(self.tdata, self.ydata)
        return self.line,
```
I get a plotting behavior like your Grapher block without the blocking during window interaction. 
Measuring the CPU load, understanding where the difference lies in the implementation or even trying to implement it in the Grapher block for testing purposes is unfortunately currently beyond my Python skill level. Maybe in the future.

Please don't get me wrong here: This is not intended as a request to implement something or that I expect anything. It is just intended as: I find this looks interesting, maybe you find it interesting too.

Martin

**Comment by WeisLeDocto** [comment]
Thank you for sharing the example, I think I never came across this specific one.
I remember testing a similar solution in `matplotlib` a while ago, but for some reason I wasn't very satisfied with it.

Might be an avenue worth exploring when we try to improve the performance of the Grapher Block, but that won't be before long. Also, investigating the Bokeh module seems more promising in term of performance improvement so it'll likely have priority.

Weis
