### ISSUE TITLE
Displayer's position in the Camera block

### ISSUE THREAD

**Issue by nicolas-goeman** [LaboratoireMecaniqueLille/crappy#47]
Hi, 

I'm new to crappy and I want to use it for Computer Vision applications. I was working on basic example which consists in:
1) Retrieving the image from my webcam
2) Apply hand detection using some external libraries
3) Adding the centroid of the hand on the image as a red dot on the image
4) Display this modified image

In order to do so I reused the Camera block as a basis and I do my whole process of hand detection in the _additional_loop function. However, I cannot use the Displayer of the base class since it is called before the call of _additional_loop. Therefore, I disabled the Displayer in the base class and create my own displayer in my class. I then use this new Displayer in my _additional_loop.

So my question is about the position of the Displayer. Shouldn't it be placed after this _additional_loop call so that we can display a modified version of the image ?

I also tried to see if there were other blocks in order to display images that could for example be sent my the Camera block but I could not find something like that. Let me known I am missing something (which would not be surprising since I am new to crappy).

I hope my problem has been explained clearly.

Thanks a lot!

Nicolas

**Comment by WeisLeDocto** [comment]
Hi Nicolas,

Your description is quite clear, I understand your problem.
Based on the description you're giving, I assume that you're using a clone of the [master](https://github.com/LaboratoireMecaniqueLille/crappy/tree/master) branch, or one of the `1.5.*` releases.

There is currently no solution to achieve precisely what you want to do in Crappy v1.5.
It could however be possible to do it in Crappy v2.0 with minor changes, so I advise you to switch to a clone of the [develop](https://github.com/LaboratoireMecaniqueLille/crappy/tree/develop) branch, or to one of the `2.0.0.dev*` releases.
As I'm currently updating Crappy from v1.5 to v2.0, I avoid starting any development on  v1.5.
I am, however, also finishing the documentation for v2.0, and some aspects related to your problem are not fully documented yet.

Note that the stable release of version `2.0.0` should be published in less than a month from now.
Also, note that in v2.0 the entire environment for image acquisition and processing has been heavily optimized, with significant performance improvements.
There is already quite some documentation for v2.0, available [on ReadTheDocs](https://crappy.readthedocs.io/en/develop/), as well as a number of [working examples](https://github.com/LaboratoireMecaniqueLille/crappy/tree/develop/examples).

The steps to follow for achieving something similar to what you want to do, in v2.0, are the following : 
- You first create a child of the [CameraProcess](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/blocks/camera_processes/camera_process.py) class, that performs your image processing.
- Then, you create a Block, child of the [Camera Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/blocks/camera.py), that sets your CameraProcess as the Process performing image processing. See the [GPUCorrel Block](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/blocks/gpu_correl.py) for a simple example. This new Block is the one that you instantiate in the script that you run.
- Your child of CameraProcess will be able to use the [_send_box](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/blocks/camera_processes/camera_process.py#L335) method, originally designed for sending the bounding box of tracked spots for video-extensometry. It is currently designed to send [SpotsBoxes](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/tool/camera_config/config_tools/spots_boxes.py) objects, that contains [Box](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/tool/camera_config/config_tools/box.py) objects. The Process in charge of the display has a [_draw_box](https://github.com/LaboratoireMecaniqueLille/crappy/blob/75494f199eccec9fd2539b6899eff111d4923e2c/src/crappy/blocks/camera_processes/display.py#L261) method that adds an overlay on the displayed images, based on the Boxes it receives. In the end, the displayed overlay gives indications on how the image processing is performing.

Following these steps, you can for now only send SpotBoxes objects and draw one or several Boxes on top of the displayed images. You could maybe, in a first time, try to draw small boxes instead of red dots. This way you can start working directly from the existing API.

In the meantime, if you're interested, I can modify Crappy as follows for release in version `2.0.0.dev4` :

- [ ] Define a generic container object (let's call it ToDraw for now), of which Box would be a subclass
- [ ] All objects sent by the `_send_box` method would now be collections of ToDraw objects
- [ ] ToDraw and its children define a method (let's cal it `__draw__` for now) that draws their object on top of the image to display
- [ ] The `_draw_box` method of the Displayer CameraProcess now calls `__draw__` on the ToDraw objects it receives
- [ ] The `_send_box` and `_draw_box` methods are renamed to remove the reference to boxes

Tell me if such a solution would fit your needs.

> Shouldn't it be placed after this _additional_loop call so that we can display a modified version of the image ?

Regarding this specific question, I think that in v2.0 the possibility to add overlays is a good way to control the quality of the original images while also including information from the image processing.

Hope my answer helps,
Weis

**Comment by nicolas-goeman** [comment]
Hi,

Thanks a lot for your complete answer. 

I was indeed using the older version of Crappy (which I got from pip) on Windows. I switched to ubuntu and cloned the develop branch. Thanks to your instructions I managed to plot theses boxes as overlay on the original image which is nice! Thanks a lot for that. It could be nice to have this architecture based on several ToDraw objects in order to be able to draw many figures such as circles, squares, ellipses, etc.

However, it could still be useful to have another option to draw outputs of processes that completely change the original image. I am currently thinking of PCA for example which I will use in future works. In that case the above tools are too limited.
I have no idea if it is a good idea or even feasible in Crappy regarding the architecture of the library but a new block (let's call it Visualizer) that could be able to receive images and display them in the same manner as the Grapher block might be very useful.
It is still interesting to have the 2 approaches mentionned earlier:
- Using ToDraw object for very simple overlays
- Using the Visualizer to plot more complex image processing

Thanks a lot again for you clear and useful answer!

Nicolas

**Comment by WeisLeDocto** [comment]
Glad to hear that you were able to draw boxes as an overlay using the develop version !
I'll create a branch right now to add the changes I mentioned in my previous answer.
Should be merged in the coming weeks.

Regarding the display of the processed images, it' not as simple as it may seem. We cannot have images transferred through Links, because the underlying [Pipe](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe) tend to overflow when transferring large images. That's one of the big limitations of v1.5 by the way.
Instead, we chose to use [shared Arrays](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Array) to transfer images, only internally to the Camera Block. This solution can transfer images of any size, provided that the size doesn't change and is known at the end of the `prepare()` method of Camera (Arrays can be shared until the end of `prepare()` **within the Camera Block**).

Because the existing Array is for sharing the original acquired images, there would need to be a second Array for sharing the new image. The Displayer CameraProcess would then have to "plug" on that second Array rather than on the first one. Then what if we want to record the new images as well ? Following this path, we would quickly end up with a mini Block/Link layout inside the Camera Block, itself part of the bigger Block/Link layout of Crappy. For now I don't see any way to implement that in a clear and user-friendly way, maybe you have ideas ?

A workaround would be to have two types of Links, one for linear data relying on Pipes and one for images relying on Arrays. It could be quite elegant, with a single `crappy.link()` method featuring automatic detection of the correct type to instantiate. However, it implies that the size and dtype of the images have to be known upfront and given every time, so that the Array can be shared during `__init__` (Arrays cannot be shared anymore **between different Blocks** once `prepare()` starts). I think that's too much to ask for most users who don't need complex image processing schemes. Again, if you have ideas, I'm open to suggestions !

And regarding the issue with Mediapipe, I suspect it has something to do with the now heavily parallelized architecture of the Camera Block in v2.0, but I cannot tell for sure without checking the code. Please open a new Issue for this specific question if you want to further investigate.

Weis

**Comment by WeisLeDocto** [comment]
Hi Nicolas,

I've brought the aforementioned modifications to the module.
I'll merge the corresponding branch now, and close this issue.

The following code works fine on my setup (Ubuntu 22.04, Python 3.10) :
```
# coding: utf-8

import crappy
import random


class BlackSquare(crappy.tool.camera_config.Overlay):

  def draw(self, img):

    img_width, img_height, *_ = img.shape
    size = min(img_width // 5, img_height // 5)

    top_x = random.randint(img_width // 3, 2 * img_width // 3)
    top_y = random.randint(img_height // 3, 2 * img_height // 3)

    for line in ((i, slice(top_y, top_y + size))
                 for i in range(top_x, top_x + size + 1)):
      img[line] = 0


class DemoProcess(crappy.blocks.camera_processes.CameraProcess):

  def _loop(self):

    if not self._get_data():
      return

    self._send_to_draw((BlackSquare(),))


class DemoBlock(crappy.blocks.Camera):

  def prepare(self):

    self._process_proc = DemoProcess(log_queue=self._log_queue,
                                     log_level=self._log_level)
    super().prepare()


if __name__ == '__main__':

  cam = DemoBlock('FakeCamera',
                  display_images=True,
                  save_images=False,
                  freq=20,
                  displayer_framerate=20,
                  display_freq=True)

  stop = crappy.blocks.StopButton()

  crappy.start()
```

I will soon add a tutorial section describing the instantiation of custom Camera Blocks, and release the `2.0.0.dev4` version containing the modifications.
There will be a few more changes to the `CameraProcess` object before version `2.0.0`, this will be detailed in the corresponding tutorial section.

Weis
