### ISSUE TITLE
Remove offset in IOBlocks ?

### ISSUE THREAD

**Issue by Annidala** [LaboratoireMecaniqueLille/crappy#9]
Dear Crappy developers,

I couldn't help but notice that there is no offset management on IO blocks. Let me explain: we have a great traction machine running on Raspberry. The loadcell measure goes through the NAU7802, whose block is already implemented in Crappy. 
As an experimenter, I would prefer the measured forces to be zero at the beginning of the test (when there is no specimen between the clamps), i.e. the offset to be automatically removed. The Comedi and Labjack blocks already have an option called "make_zero", could this be an option for the NAU7802 or even would it be possible to add this option in the IOBlocks ?

Thank you for your consideration,

**Comment by WeisLeDocto** [comment]
Hello Annidala,

I'm not forgetting about you, I just didn't have much time lately to implement your requested improvement.
It will be done over the next few weeks, I'll keep you updated !

Weis

**Comment by WeisLeDocto** [comment]
Dear Annidala,

I took some time to address your improvement request and came up with two solutions.

- First, I added the Offset Modifier (commit 85e8e93) that allows to offset **only the values flowing through a link**. So it has no effect on the acquired values, it only has an impact on the data received by the downstream block. The offset is determined based only on the first received value, so it is not very accurate.
- Alternatively, I refactored the IOBlock and the base InOut class and used this opportunity to add the `make_zero_delay` argument for all IOBlocks (commit b98883c). It acquires data for a given amount of time before the test starts and uses it to offset all the output labels to zero. **It permanently modifies the data acquired by the block**. Since the offset is calculated based on many values, it is normally quite accurate.

I hope it meets your enhancement request, otherwise let me know.
Unfortunately I made big changes in the code and I'm not planning on releasing a version containing these improvements any soon. They will be part of the next big release, either 1.6.0 or 2.0.0, that I'm expecting to release by the end of summer.
The Offset Modifier can nevertheless be copy-pasted and integrated almost as-is in a test script.

Weis

**Comment by Annidala** [comment]
Dear WeisLeDocto,

I agree with you: a single point offset with the offset modifier clearly lacks accuracy.I'm looking forward to the release of the new IOblock this summer to use it !
Thank you very much for addressing this issue :)

Dala
